// <auto-generated />
using System;
using FormCreateProject.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormCreateProject.Migrations
{
    [DbContext(typeof(FormDbContext))]
    [Migration("20230426204355_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContentQuestion", b =>
                {
                    b.Property<Guid>("ContentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContentsId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("ContentQuestion");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CretedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5dacec1-85d1-41ef-9660-0d1114b30bba"),
                            DataType = "STRING",
                            Name = "Ad",
                            Required = true
                        },
                        new
                        {
                            Id = new Guid("1224975c-fc3a-4149-9d0b-acae3a4cf74c"),
                            DataType = "STRING",
                            Name = "Soyad",
                            Required = true
                        },
                        new
                        {
                            Id = new Guid("dbf19620-563d-4cf7-a975-6af6690e69d8"),
                            DataType = "NUMBER",
                            Name = "Yaş",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("766ead87-0c87-4f0f-820d-80f6f018a031"),
                            DataType = "DATETIME",
                            Name = "Doğum Tarihi",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("221cadb8-9628-4348-a114-7aaa2041881c"),
                            DataType = "STRING",
                            Name = "E-posta",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("4eb195bb-f563-4a2e-980c-8017d9ae69b2"),
                            DataType = "STRING",
                            Name = "Telefon",
                            Required = false
                        });
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fbb97d1-5316-469c-90ef-0d5a1c178cff"),
                            FirstName = "Büşra",
                            LastName = "Yumuşakkaya",
                            Name = "BusraYumusakkaya",
                            Password = "Busra123."
                        });
                });

            modelBuilder.Entity("ContentQuestion", b =>
                {
                    b.HasOne("FormCreateProject.Entities.Concrete.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormCreateProject.Entities.Concrete.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Content", b =>
                {
                    b.HasOne("FormCreateProject.Entities.Concrete.Form", "Form")
                        .WithMany("Contents")
                        .HasForeignKey("FormId");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Form", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
