// <auto-generated />
using System;
using FormCreateProject.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormCreateProject.Migrations
{
    [DbContext(typeof(FormDbContext))]
    partial class FormDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContentQuestion", b =>
                {
                    b.Property<Guid>("ContentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContentsId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("ContentQuestion");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CretedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95b2e335-e208-4650-9005-04e89d3c1134"),
                            DataType = "STRING",
                            Name = "Ad",
                            Required = true
                        },
                        new
                        {
                            Id = new Guid("927497fc-b604-44cc-a8c1-7a6d2a9bcda2"),
                            DataType = "STRING",
                            Name = "Soyad",
                            Required = true
                        },
                        new
                        {
                            Id = new Guid("a05c7265-cd9f-42eb-8f8b-285f57d2a214"),
                            DataType = "NUMBER",
                            Name = "Yaş",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("446f656e-12cf-442b-af66-e5f59aa923ee"),
                            DataType = "DATETIME",
                            Name = "Doğum Tarihi",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("f5ee8d42-c449-4671-a191-8564117a6e21"),
                            DataType = "STRING",
                            Name = "E-posta",
                            Required = false
                        },
                        new
                        {
                            Id = new Guid("73d629fc-e9f7-4252-adfc-ad25af3c51e5"),
                            DataType = "STRING",
                            Name = "Telefon",
                            Required = false
                        });
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("206e12c8-9ed3-4751-9868-95888a220a02"),
                            FirstName = "Büşra",
                            LastName = "Yumuşakkaya",
                            Name = "BusraYumusakkaya",
                            Password = "Busra123."
                        });
                });

            modelBuilder.Entity("ContentQuestion", b =>
                {
                    b.HasOne("FormCreateProject.Entities.Concrete.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormCreateProject.Entities.Concrete.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Content", b =>
                {
                    b.HasOne("FormCreateProject.Entities.Concrete.Form", "Form")
                        .WithMany("Contents")
                        .HasForeignKey("FormId");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormCreateProject.Entities.Concrete.Form", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
